### PR TITLE
ES6

### PR DESCRIPTION
**Pull request by josh**
Sprockets 4.x will have first class support for ES6 via [6to5](https://6to5.github.io).

/cc @dgraham @sebmck @thejameskyle

### CODE REVIEW

**Comment by andrewhao** [comment]
:+1: excited for this!

**Comment by thegrubbsian** [comment]
Also very excited for this!

**Comment by lidonghua** [comment]
That's really cool!

**Comment by alex88** [comment]
Oh great!

**Comment by yordis** [comment]
:+1:
@josh is this in Rails or in development?

**Comment by tony612** [comment]
:+1:

**Comment by wjp2013** [comment]
:+1:

**Comment by 42thcoder** [comment]
:+1:

**Comment by 007lva** [comment]
:+1:

**Pull request merged**
